# Generated by Django 4.2.2 on 2023-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_caption', models.TextField()),
                ('image_or_video_content', models.FileField(upload_to='static/image/')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('location_post', models.CharField(max_length=100)),
            ],
        ),
    ]
