# Generated by Django 4.2.2 on 2023-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location_post',
            field=models.CharField(choices=[('Palakkad', 'Palakkad'), ('Calicut', 'Calicut'), ('Kochi', 'Kochi'), ('Wayanad', 'Wayanad')], max_length=100),
        ),
    ]
